### PR TITLE
Update specs and GitHub actions config

### PR DESCRIPTION
**Pull request by davidtaylorhq**
- **Update specs to use Discourse patterns, and avoid stubs**
  This means that the specs are a much closer match to production, and should pick up any breaking changes to Discourse core

- **Update GitHub Actions config**
  This matches the discourse-plugin-skeleton config
  https://github.com/discourse/discourse-plugin-skeleton/blob/main/.github/workflows/plugin-tests.yml

(Note these will fail until #67 is merged)

### CODE REVIEW

**Comment by jonmbake** [comment]
@davidtaylorhq Can you rebase master?

**Comment by davidtaylorhq** [comment]
Rebased and passing 🚀

**Comment by jonmbake** [comment]
@davidtaylorhq Any ideas why the [scheduled action is failing](https://github.com/jonmbake/discourse-ldap-auth/runs/4686652298?check_suite_focus=true) on the _Create and migrate database_ step? The following error shows:

```
ArgumentError: No setting named 'discourse_narrative_bot_enabled' exists
/__w/discourse-ldap-auth/discourse-ldap-auth/lib/site_settings/defaults_provider.rb:58:in `set_regardless_of_locale'
/__w/discourse-ldap-auth/discourse-ldap-auth/config/environments/test.rb:73:in `block (3 levels) in <main>'
```

**Comment by davidtaylorhq** [comment]
Oh, sorry about that @jonmbake - looks like our workflow template doesn't support running on a schedule (`github.event.repository.name` doesn't seem to be populated)

As you've done, removing the schedule option is probably best for now :+1:

**Pull request merged**
